type Car = {
    model: string,
    price: number,
    category: string,
    manufactorer: string,
    color: string,
    transmissionType: string,
    numberOfSeats: number,
}

export const cars: Car[] = [
    {
      model: 'Accord',
      price: 95.0,
      category: 'SEDAN',
      manufactorer: 'Honda',
      color: 'Gray',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'Altima',
      price: 92.0,
      category: 'SEDAN',
      manufactorer: 'Nissan',
      color: 'Silver',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'Sonata',
      price: 90.0,
      category: 'SEDAN',
      manufactorer: 'Hyundai',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'K5',
      price: 100.0,
      category: 'SEDAN',
      manufactorer: 'Kia',
      color: 'Black',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'Mazda6',
      price: 98.0,
      category: 'SEDAN',
      manufactorer: 'Mazda',
      color: 'Red',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'Malibu',
      price: 97.0,
      category: 'SEDAN',
      manufactorer: 'Chevrolet',
      color: 'Blue',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'Model 3',
      price: 110.0,
      category: 'SEDAN',
      manufactorer: 'Tesla',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: '3 Series',
      price: 120.0,
      category: 'SEDAN',
      manufactorer: 'BMW',
      color: 'Black',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: '911 Carrera',
      price: 200.0,
      category: 'SPORT',
      manufactorer: 'Porsche',
      color: 'Red',
      transmissionType: 'Manual',
      numberOfSeats: 2,
    },
    {
      model: 'F8 Tributo',
      price: 250.0,
      category: 'SPORT',
      manufactorer: 'Ferrari',
      color: 'Yellow',
      transmissionType: 'Automatic',
      numberOfSeats: 2,
    },
    {
      model: 'M4 Competition',
      price: 150.0,
      category: 'SPORT',
      manufactorer: 'BMW',
      color: 'Blue',
      transmissionType: 'Automatic',
      numberOfSeats: 2,
    },
    {
      model: 'Corvette',
      price: 140.0,
      category: 'SPORT',
      manufactorer: 'Chevrolet',
      color: 'Orange',
      transmissionType: 'Automatic',
      numberOfSeats: 2,
    },
    {
      model: 'Suburban',
      price: 130.0,
      category: 'SUV',
      manufactorer: 'Chevrolet',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 8,
    },
    {
      model: 'Highlander',
      price: 125.0,
      category: 'SUV',
      manufactorer: 'Toyota',
      color: 'Silver',
      transmissionType: 'Automatic',
      numberOfSeats: 7,
    },
    {
      model: 'Explorer',
      price: 135.0,
      category: 'SUV',
      manufactorer: 'Ford',
      color: 'Black',
      transmissionType: 'Automatic',
      numberOfSeats: 7,
    },
    {
      model: 'Grand Cherokee',
      price: 140.0,
      category: 'SUV',
      manufactorer: 'Jeep',
      color: 'Green',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'Odyssey',
      price: 115.0,
      category: 'MPV',
      manufactorer: 'Honda',
      color: 'Silver',
      transmissionType: 'Automatic',
      numberOfSeats: 6,
    },
    {
      model: 'Sienna',
      price: 120.0,
      category: 'MPV',
      manufactorer: 'Toyota',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 7,
    },
    {
      model: 'Pacifica',
      price: 118.0,
      category: 'MPV',
      manufactorer: 'Chrysler',
      color: 'Blue',
      transmissionType: 'Automatic',
      numberOfSeats: 7,
    },
    {
      model: 'C4 Picasso',
      price: 105.0,
      category: 'MPV',
      manufactorer: 'Citroën',
      color: 'Red',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'Mustang',
      price: 150.0,
      category: 'COUPE',
      manufactorer: 'Ford',
      color: 'Blue',
      transmissionType: 'Manual',
      numberOfSeats: 4,
    },
    {
      model: 'A5',
      price: 145.0,
      category: 'COUPE',
      manufactorer: 'Audi',
      color: 'Gray',
      transmissionType: 'Automatic',
      numberOfSeats: 4,
    },
    {
      model: '4 Series',
      price: 155.0,
      category: 'COUPE',
      manufactorer: 'BMW',
      color: 'Black',
      transmissionType: 'Automatic',
      numberOfSeats: 4,
    },
    {
      model: 'TT',
      price: 135.0,
      category: 'COUPE',
      manufactorer: 'Audi',
      color: 'Red',
      transmissionType: 'Manual',
      numberOfSeats: 4,
    },
    {
      model: 'Mini Cooper',
      price: 80.0,
      category: 'HATCHBACK',
      manufactorer: 'Mini',
      color: 'Yellow',
      transmissionType: 'Manual',
      numberOfSeats: 4,
    },
    {
      model: 'Golf',
      price: 85.0,
      category: 'HATCHBACK',
      manufactorer: 'Volkswagen',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    },
    {
      model: 'Focus',
      price: 75.0,
      category: 'HATCHBACK',
      manufactorer: 'Ford',
      color: 'Blue',
      transmissionType: 'Manual',
      numberOfSeats: 5,
    },
    {
      model: 'Civic Hatch',
      price: 88.0,
      category: 'HATCHBACK',
      manufactorer: 'Honda',
      color: 'Silver',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
    }
  ];

export default Car