export type Car = {
    model: string
    price: number
    category: string
    manufactorer: string
    color: string
    transmissionType: string
    numberOfSeats: number
    description: string
    colors?: string[]
    availableColors?: string[]
  }
  
export const cars: Car[] = [
    {
      model: 'Accord',
      price: 95.0,
      category: 'SEDAN',
      manufactorer: 'Honda',
      color: 'Gray',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Honda Accord is a reliable midsize sedan known for its comfortable ride and excellent fuel efficiency.',
    },
    {
      model: 'Altima',
      price: 92.0,
      category: 'SEDAN',
      manufactorer: 'Nissan',
      color: 'Silver',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Nissan Altima offers a smooth driving experience with a spacious interior and modern tech features.',
    },
    {
      model: 'Sonata',
      price: 90.0,
      category: 'SEDAN',
      manufactorer: 'Hyundai',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Hyundai Sonata combines sleek styling with a comfortable cabin and advanced safety systems.',
    },
    {
      model: 'K5',
      price: 100.0,
      category: 'SEDAN',
      manufactorer: 'Kia',
      color: 'Black',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Kia K5 is a sporty sedan with sharp handling, a refined interior, and plenty of standard equipment.',
    },
    {
      model: 'Mazda6',
      price: 98.0,
      category: 'SEDAN',
      manufactorer: 'Mazda',
      color: 'Red',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Mazda6 is celebrated for its engaging driving dynamics, upscale cabin, and elegant design.',
    },
    {
      model: 'Malibu',
      price: 97.0,
      category: 'SEDAN',
      manufactorer: 'Chevrolet',
      color: 'Blue',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Chevrolet Malibu offers a balanced ride, user‑friendly infotainment, and a roomy interior.',
    },
    {
      model: 'Model 3',
      price: 110.0,
      category: 'SEDAN',
      manufactorer: 'Tesla',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'Tesla Model 3 is an all‑electric sedan delivering brisk acceleration, long range, and cutting‑edge tech.',
    },
    {
      model: '3 Series',
      price: 120.0,
      category: 'SEDAN',
      manufactorer: 'BMW',
      color: 'Black',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The BMW 3 Series is a compact executive sedan known for its precise handling and premium interior.',
    },
    {
      model: '911 Carrera',
      price: 200.0,
      category: 'SPORT',
      manufactorer: 'Porsche',
      color: 'Red',
      transmissionType: 'Manual',
      numberOfSeats: 2,
      description: 'The Porsche 911 Carrera is an iconic sports car, offering blistering performance and timeless style.',
    },
    {
      model: 'F8 Tributo',
      price: 250.0,
      category: 'SPORT',
      manufactorer: 'Ferrari',
      color: 'Yellow',
      transmissionType: 'Automatic',
      numberOfSeats: 2,
      description: 'Ferrari F8 Tributo is a mid‑engine supercar boasting V8 power, razor‑sharp handling, and exotic flair.',
    },
    {
      model: 'M4 Competition',
      price: 150.0,
      category: 'SPORT',
      manufactorer: 'BMW',
      color: 'Blue',
      transmissionType: 'Automatic',
      numberOfSeats: 2,
      description: 'The BMW M4 Competition delivers high‑performance driving with a turbocharged engine and track‑ready chassis.',
    },
    {
      model: 'Corvette',
      price: 140.0,
      category: 'SPORT',
      manufactorer: 'Chevrolet',
      color: 'Orange',
      transmissionType: 'Automatic',
      numberOfSeats: 2,
      description: 'The Chevrolet Corvette is an American sports icon, offering V8 thrills and a mid‑engine layout.',
    },
    {
      model: 'Suburban',
      price: 130.0,
      category: 'SUV',
      manufactorer: 'Chevrolet',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 8,
      description: 'The Chevrolet Suburban is a full‑size SUV with seating for eight, a powerful engine, and vast cargo space.',
    },
    {
      model: 'Highlander',
      price: 125.0,
      category: 'SUV',
      manufactorer: 'Toyota',
      color: 'Silver',
      transmissionType: 'Automatic',
      numberOfSeats: 7,
      description: 'The Toyota Highlander is a family‑friendly SUV with three rows, solid reliability, and smooth ride.',
    },
    {
      model: 'Explorer',
      price: 135.0,
      category: 'SUV',
      manufactorer: 'Ford',
      color: 'Black',
      transmissionType: 'Automatic',
      numberOfSeats: 7,
      description: 'The Ford Explorer is a versatile SUV offering strong towing capability and a comfortable interior.',
    },
    {
      model: 'Grand Cherokee',
      price: 140.0,
      category: 'SUV',
      manufactorer: 'Jeep',
      color: 'Green',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Jeep Grand Cherokee blends off‑road prowess with upscale cabin appointments and modern tech.',
    },
    {
      model: 'Odyssey',
      price: 115.0,
      category: 'MPV',
      manufactorer: 'Honda',
      color: 'Silver',
      transmissionType: 'Automatic',
      numberOfSeats: 6,
      description: 'The Honda Odyssey is a top‑rated minivan with family‑oriented features, sliding doors, and a smooth ride.',
    },
    {
      model: 'Sienna',
      price: 120.0,
      category: 'MPV',
      manufactorer: 'Toyota',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 7,
      description: 'The Toyota Sienna is a hybrid minivan offering great fuel economy and versatile seating configurations.',
    },
    {
      model: 'Pacifica',
      price: 118.0,
      category: 'MPV',
      manufactorer: 'Chrysler',
      color: 'Blue',
      transmissionType: 'Automatic',
      numberOfSeats: 7,
      description: 'The Chrysler Pacifica features a refined interior, available hybrid powertrain, and Stow ’n Go seats.',
    },
    {
      model: 'C4 Picasso',
      price: 105.0,
      category: 'MPV',
      manufactorer: 'Citroën',
      color: 'Red',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Citroën C4 Picasso is a compact MPV with clever storage, a bright cabin, and a comfortable ride.',
    },
    {
      model: 'Mustang',
      price: 150.0,
      category: 'COUPE',
      manufactorer: 'Ford',
      color: 'Blue',
      transmissionType: 'Manual',
      numberOfSeats: 4,
      description: 'The Ford Mustang is a classic muscle coupe delivering bold styling and throaty V8 performance.',
    },
    {
      model: 'A5',
      price: 145.0,
      category: 'COUPE',
      manufactorer: 'Audi',
      color: 'Gray',
      transmissionType: 'Automatic',
      numberOfSeats: 4,
      description: 'The Audi A5 coupe offers elegant design, a high‑quality interior, and smooth, composed handling.',
    },
    {
      model: '4 Series',
      price: 155.0,
      category: 'COUPE',
      manufactorer: 'BMW',
      color: 'Black',
      transmissionType: 'Automatic',
      numberOfSeats: 4,
      description: 'The BMW 4 Series coupe is a sporty luxury car with a powerful engine and driver‑focused cabin.',
    },
    {
      model: 'TT',
      price: 135.0,
      category: 'COUPE',
      manufactorer: 'Audi',
      color: 'Red',
      transmissionType: 'Manual',
      numberOfSeats: 4,
      description: 'The Audi TT is a compact coupe known for its distinctive styling and agile handling.',
    },
    {
      model: 'Mini Cooper',
      price: 80.0,
      category: 'HATCHBACK',
      manufactorer: 'Mini',
      color: 'Yellow',
      transmissionType: 'Manual',
      numberOfSeats: 4,
      description: 'The Mini Cooper is a fun hatchback with go‑kart handling and a customizable, retro‑inspired design.',
    },
    {
      model: 'Golf',
      price: 85.0,
      category: 'HATCHBACK',
      manufactorer: 'Volkswagen',
      color: 'White',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Volkswagen Golf is a practical hatchback with a refined ride, upscale interior, and solid build quality.',
    },
    {
      model: 'Focus',
      price: 75.0,
      category: 'HATCHBACK',
      manufactorer: 'Ford',
      color: 'Blue',
      transmissionType: 'Manual',
      numberOfSeats: 5,
      description: 'The Ford Focus is an agile compact car offering sharp handling and good fuel economy.',
    },
    {
      model: 'Civic Hatch',
      price: 88.0,
      category: 'HATCHBACK',
      manufactorer: 'Honda',
      color: 'Silver',
      transmissionType: 'Automatic',
      numberOfSeats: 5,
      description: 'The Honda Civic Hatch is a sporty compact hatchback with a spacious interior and strong reliability.',
    },
  ]

